name: Question Label Workflow

on:
  issues:
    types: [labeled]

jobs:
  handle_question:
    if: github.event.label.name == 'question'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Commit Message
        id: get_commit
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "::set-output name=message::$commit_message"

      - name: Send Commit Message to OpenAI
        id: openai_response
        run: |
          response=$(curl -s -X POST "https://api.openai.com/v1/engines/davinci/completions" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"prompt\": \"${{ steps.get_commit.outputs.message }}\", \"max_tokens\": 150}")
          answer=$(echo $response | jq -r '.choices[0].text')
          answer_escaped=$(echo "$answer" | sed ':a;N;$!ba;s/\n/__NEWLINE__/g')
          echo "ANSWER=$answer_escaped" >> $GITHUB_ENV

      - name: Check Response and Comment on Issue
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            let responseText = process.env.ANSWER;
            responseText = responseText.split('__NEWLINE__').join('\n');
            let commentBody = '';

            if (responseText.includes('not enough information')) {
              commentBody = '@GregorBiswanger eventuell kannst du hierbei helfen?';
            } else {
              commentBody = responseText;
            }

            github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
