name: Move Issue to Review

on:
  pull_request:
    types: [assigned]

jobs:
  move-issue-to-review:
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to Review column
        uses: actions/github-script@v5
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const repoName = context.repo.repo;
            const ownerName = context.repo.owner;

            // GraphQL query to get linked issues (items) from the pull request
            const query = `
              query($owner: String!, $repo: String!, $prNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $prNumber) {
                    projectItems(first: 10) {
                      nodes {
                        id
                      }
                    }
                  }
                }
              }
            `;

            const variables = {
              owner: ownerName,
              repo: repoName,
              prNumber: prNumber
            };

            const response = await github.graphql(query, variables);
            const linkedItems = response.repository.pullRequest.projectItems.nodes;

            // Replace with your project field ID and option ID for the Review column
            const fieldId = '1';
            const optionId = '9fbcdcc0';

            for (const item of linkedItems) {
              // GraphQL mutation to move the item to the Review column
              const mutation = `
                mutation($itemId: ID!, $fieldId: ID!, $optionId: ID!) {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: $itemId,
                    fieldId: $fieldId,
                    value: {
                      singleSelectOptionId: $optionId
                    }
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;

              const mutationVariables = {
                itemId: item.id,
                fieldId: fieldId,
                optionId: optionId
              };

              await github.graphql(mutation, mutationVariables);
            }