name: Move Issue to Review

on:
  pull_request:
    types: [assigned]

jobs:
  move-issue-to-review:
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to Review
        uses: actions/github-script@v5
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const repoName = context.repo.repo;
            const ownerName = context.repo.owner;

            // Get linked issues from the pull request
            const { data: linkedIssues } = await github.rest.issues.listForRepo({
              owner: ownerName,
              repo: repoName,
              pull_request: prNumber
            });

            if (linkedIssues.length === 0) {
              console.log("Keine verknüpften Issues gefunden.");
            } else {
              console.log("Gefundene verknüpfte Issues:");
              linkedIssues.forEach(async issue => {
                console.log(`Issue #${issue.number}: ${issue.title}`);

                // Add 'review' label to the issue
                await github.rest.issues.addLabels({
                  owner: ownerName,
                  repo: repoName,
                  issue_number: issue.number,
                  labels: ['review'] // Replace 'review' with the label you want to add
                });
              });
            }
