name: Set Linked Issue to Review

on:
  pull_request:
    types: [assigned]

jobs:
  set-issue-to-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set linked issue to Review
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = ${{ github.event.pull_request.number }};
          const repo = context.repo.repo;
          const owner = context.repo.owner;

          // Get linked issues from the PR
          const linkedIssues = await github.graphql(`
            query($owner: String!, $repo: String!, $prNumber: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $prNumber) {
                  closingIssuesReferences(first: 10) {
                    nodes {
                      number
                    }
                  }
                }
              }
            }
          `, {
            owner,
            repo,
            prNumber
          });

          const issues = linkedIssues.repository.pullRequest.closingIssuesReferences.nodes;

          // Get the details of the fields
          const projectData = await github.graphql(`
            query($owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                projectsV2(first: 1) {
                  nodes {
                    fields(first: 10) {
                      nodes {
                        id
                        name
                        settings
                        dataType
                        ... on ProjectV2SingleSelectField {
                          options {
                            id
                            name
                          }
                        }
                        ... on ProjectV2TextField {
                          text
                        }
                        ... on ProjectV2NumberField {
                          number
                        }
                        ... on ProjectV2DateField {
                          date
                        }
                      }
                    }
                  }
                }
              }
            }
          `, {
            owner,
            repo
          });

          // Output the details of the fields
          console.log(JSON.stringify(projectData, null, 2));
