name: Move Issue to Review

on:
  pull_request:
    types: [assigned]

jobs:
  move-issue-to-review:
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to Review column
        uses: actions/github-script@v5
        with:
          script: |
            const github = require('@actions/github');
            const context = github.context;
            const token = process.env.GITHUB_TOKEN;
            const octokit = github.getOctokit(token);

            const prNumber = context.payload.pull_request.number;
            const repoName = context.repo.repo;
            const ownerName = context.repo.owner;

            // Get linked issues from the pull request
            const { data: linkedIssues } = await octokit.rest.issues.listForRepo({
              owner: ownerName,
              repo: repoName,
              pull_request: prNumber
            });

            // Replace with your project ID and column ID
            const projectId = '1';
            const reviewColumnId = '9fbcdcc0';

            for (const issue of linkedIssues) {
              // Move the issue to the Review column
              await octokit.rest.projects.moveCard({
                card_id: issue.id,
                column_id: reviewColumnId,
                position: 'top'
              });
            }